env:
    # Device
    DT_LINK: https://github.com/NRanjan-17/device_gta4l_twrp.git
    DEVICE: gta4l
    OEM: samsung
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: recovery.img

    # Not Recommended to Change
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[565be251908fce71ca500a85893f808586848a6fd1eeee7ecaa2d77cc67fbe01b62108989459a16cdb73ddfbe7a1b7db]
    TG_TOKEN: ENCRYPTED[2f687719dbda3c144a3c6ca0f9a891ab57f919f1d49619d9e89598d205a8df3fdcc5ba5843579a1e9d1f7c9ae495aee1]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/alone0316/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/sync.sh | bash
      - (bash -c "$command" | tee sync.txt) || true
      - a=$(grep 'Cannot remove project' sync.txt || true)
      - b=$(grep "^fatal: remove-project element specifies non-existent project" sync.txt || true)
      - if [[ $a == *'Cannot remove project'* ]]
      - then
      - a=$(echo $a | cut -d ':' -f2)
      - rm -rf $a
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
      - elif [[ $b == *'remove-project element specifies non-existent'* ]]
      - then exit 1
      - else
      - (repo forall -c 'git checkout .' && bash -c "$only_sync") || (find -name shallow.lock -delete && find -name index.lock -delete && bash -c "$only_sync")
      - fi
      - rm -rf sync.txt

  Build_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/upload.sh | bash
